name: 贴吧签到

on:
  schedule:
    - cron: '0 1 * * *' # 每天UTC时间的01:00执行（北京时间上午9点）
  workflow_dispatch:

jobs:
  sign_in:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install requests module
        run: pip install requests
      - name: Run script
        env:
          BARK_URL: ${{ secrets.BARK_URL }}
          BDUSS: ${{ secrets.BDUSS}}
        run: python Tieba_Sign_in.py